# NumPy 

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

  - a powerful N-dimensional array object
  - sophisticated (broadcasting) functions
  - tools for integrating C/C++ and Fortran code
  - useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy is licensed under the [BSD](http://www.numpy.org/license.html#license) license, enabling reuse with few restrictions.

## Installation Guide

**It is strongly recommended that you install Python using the Anaconda distribution to make sure all underlying dependencies work with conda install. If you have already installed Anaconda, install NumPy by opening your terminal(for MAC Users) or ANACONDA Command Prompt(for Windows Users) and type the following command - **
    
    conda install numpy
    
**If you are unable to install ANACONDA due to restrictions, please refer to [Numpy's official documentation on installation steps.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy Package

Once NumPy Package is installed successfully, you can import it to the current Python session using the following code:

In [1]:
import numpy as np        # Call the NumPy package using np. notation after executing the same

# PART 1 - Intro to Arrays in NumPy

Numpy has a ton of built-in functions that are useful for Data Scientists & Python Programmers alike.

We shall cover some of the most important topics in Numpy: 

  - Arrays ( using Vectors & Matrices ) 
  - Number Generation Concepts

# Numpy Arrays

NumPy arrays are the one of the most widely used data structuring techniques by Data Scientists. 

Numpy arrays are of two types: Vectors and Matrices. 

Vectors are 1-dimensional arrays and matrices are 2-dimensional arrays(A Matrix can still possess a single row or a column).

We shall begin our learning with how to create NumPy Arrays.

## Creating simple NumPy Array Structures

We could create a simple Array by using a list of values or a list of "List of values".

In [2]:
simple_list = [101,102,103,104,105,106,107,108,109,110]
simple_list

[101, 102, 103, 104, 105, 106, 107, 108, 109, 110]

In [3]:
np.array(simple_list)

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [4]:
simple_list_of_lists = [[10,11,12],[20,21,22],[30,31,32]]
simple_list_of_lists

[[10, 11, 12], [20, 21, 22], [30, 31, 32]]

In [5]:
np.array(simple_list_of_lists)

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

**There are multiple built-in methods to generate Arrays**

### arange

Return evenly spaced values within a given interval as input.

In [6]:
np.arange(0,20)         # Return values 0 to 19. Start value is 0 which is included, the stop value provided is 20 which is not included



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
np.arange(0,20,4)       # Specify start, stop and step values as input

array([ 0,  4,  8, 12, 16])

### 0's and 1's

Generate arrays of 0's or 1's

In [8]:
np.zeros(10)            # Specify the count of 0's required in the array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((4,3))         # Specify the number of rows by columns - 4 rows and 3 cols in this example

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(10)            # Specify the count of 1's required in the array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones((4,5))         # Specify the number of rows by columns - 4 rows and 5 cols in this example

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [12]:
np.linspace(0,20,5)    # Specify the start, stop and number values needed between them. Please note the stop value is also considered in this case



array([ 0.,  5., 10., 15., 20.])

In [13]:
np.linspace(0,20,100)

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

## eye

Return a 2-D array with ones on the diagonal and zeros elsewhere. Also called an identity matrix

In [14]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Random 

Numpy has lots of options to create random numbered arrays:

### rand
Create an array of the given shape and populate it with random variables derived from a uniform distribution between `[0, 1)`.

In [15]:
np.random.rand(5)

array([0.08299432, 0.85637232, 0.30636743, 0.561744  , 0.34125509])

In [16]:
np.random.rand(3,2)

array([[0.35262559, 0.15987108],
       [0.61127399, 0.09874373],
       [0.56002234, 0.01916105]])

### randn

Return a variable (or a set of variables) from the "Standard Normal" distribution. Unlike rand which is from a uniform distribution: 

A standard Normal Distribution has mean 0 and SD of 1 as we know.

In [17]:
np.random.randn(5)

array([ 1.02046915,  2.84230641, -0.13027656, -0.72640525, -0.14244716])

In [18]:
np.random.randn(3,2)

array([[-0.46552788, -1.45422382],
       [-0.05891178,  1.29700045],
       [ 0.03055257, -0.86804274]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [19]:
np.random.randint(5,20)       # Returns one rand integer between the values 5 & 19(20 is excluded)

6

In [20]:
np.random.randint(20,50,5)  # Returns  5 rand integers between 20 & 49(50 is excluded)

array([37, 45, 38, 31, 41])

## Array Attributes and Methods for an array

Let us look at some important attributes and methods for an array.

In [21]:
sample_array = np.arange(30)
rand_array = np.random.randint(0,100,20)

In [22]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
rand_array

array([ 9, 64, 16, 98, 76, 71, 24, 43,  7, 69, 82, 17, 18, 79, 93, 87, 10,
       13, 70, 40])

## Reshape
Returns an array containing the same data with a new shape.

In [24]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [25]:
rand_array

array([ 9, 64, 16, 98, 76, 71, 24, 43,  7, 69, 82, 17, 18, 79, 93, 87, 10,
       13, 70, 40])

In [26]:
rand_array.max()

98

In [27]:
rand_array.argmax()

3

In [28]:
rand_array.min()

7

In [29]:
rand_array.argmin()

8

## Shape

Shape is an attribute that arrays have. It is not a method.

In [30]:
# Vector
sample_array.shape

(30,)

In [31]:
# Output has two sets of brackets - which indicates a matrix and not a vector
sample_array.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [32]:
sample_array.reshape(1,30).shape

(1, 30)

In [33]:
sample_array.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [34]:
sample_array.reshape(30,1).shape

(30, 1)

### dtype

You could retrieve the data type of the object in an array using dtype.

In [35]:
sample_array.dtype

dtype('int32')

In [36]:
sample_array2 = np.random.randn(4,4)

sample_array2

array([[ 0.55513056, -2.6397247 , -0.67744752,  1.03115623],
       [-0.52876158,  2.03355696,  0.5379479 ,  0.3165821 ],
       [-0.47344207,  0.31098734,  0.02193972,  0.04779659],
       [-1.1044735 , -2.38993526,  1.64122797, -0.69763759]])

In [37]:
sample_array2.T          # Transpose a matrix

array([[ 0.55513056, -0.52876158, -0.47344207, -1.1044735 ],
       [-2.6397247 ,  2.03355696,  0.31098734, -2.38993526],
       [-0.67744752,  0.5379479 ,  0.02193972,  1.64122797],
       [ 1.03115623,  0.3165821 ,  0.04779659, -0.69763759]])

# Part 2 - NumPy Indexing & Selection

We will now learn how to select objects or groups of objects from an array

In [38]:
#Create a sample array with 11 values
sample_array = np.arange(10,21)

In [39]:
#Show
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## Using brackets for Indexing & Selection


In [40]:
#Get the value at index position 8 from above sample array - Indexing starts from 0 and not 1
sample_array[8]

18

In [41]:
#Get values from a range selection
sample_array[0:3]

array([10, 11, 12])

In [42]:
#Get values from specific index positions
sample_array[[0,4,7]]

array([10, 14, 17])

## Broadcasting

NumPy arrays have the capability of Broadcasting values as seen below

In [43]:
#Setting a fixed value 100 using index range (Broadcasting)
sample_array[1:2]=100

#Show
sample_array

array([ 10, 100,  12,  13,  14,  15,  16,  17,  18,  19,  20])

In [44]:
# Reset array, we shall see the need for reset
sample_array = np.arange(10,21)

#Show
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [45]:
#Subsetting an array
subset_sample_array = sample_array[0:7]

#Output of the subset
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [46]:
#Change the values in the subset
subset_sample_array[:]=1001

#Show subset output again
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# Please Note that the changes in the subset has affected the original sample_array as well

In [47]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

# Data is not copied when we subset, it is a sub-view of the original array 
# This is a feature by default in order to avoid memory problems

In [48]:
#To get a copy, we need to use the copy function
copy_array = sample_array.copy()

copy_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

## Indexing a Matrix - 2 dimensional arrays

The general formats used are 

**sample_matrix[row][col]** 

or

**sample_matrix[row,col]**

We will use the second option as standard.

In [49]:
sample_matrix = np.array(([50,200,5,10],[10,35,50,15],[25,100,145,120],[105,25,65,80]))

#Show output
sample_matrix

array([[ 50, 200,   5,  10],
       [ 10,  35,  50,  15],
       [ 25, 100, 145, 120],
       [105,  25,  65,  80]])

In [50]:
#Indexing rows
sample_matrix[1]


array([10, 35, 50, 15])

In [51]:
# Getting an individual element value from the matrix - Method 1
sample_matrix[1][2]

50

In [52]:
# Getting an individual element value from the matrix - Method 2
sample_matrix[1,2]

50

In [53]:
# Slicing matrix

#Shape (3,3) from top right corner
sample_matrix[:3,1:]

array([[200,   5,  10],
       [ 35,  50,  15],
       [100, 145, 120]])

In [54]:
#Shape bottom row - Extract values from last row only
sample_matrix[3]

array([105,  25,  65,  80])

In [55]:
#Shape bottom row - Including column selection (Alternate to above)
sample_matrix[3,:]

array([105,  25,  65,  80])

### Custom Indexing of Matrix

Custom or Fancy indexing allows you to select entire rows or columns specifically in interest.

In [56]:
#Set up a sample matrix
sample_matrix = np.array(([50,200,5,10,160],[170,10,35,50,15],[125,25,100,145,120],[100,105,25,65,80],[250,15,25,30,100]))

sample_matrix

array([[ 50, 200,   5,  10, 160],
       [170,  10,  35,  50,  15],
       [125,  25, 100, 145, 120],
       [100, 105,  25,  65,  80],
       [250,  15,  25,  30, 100]])

In [57]:
sample_matrix[:,(1,3)]

array([[200,  10],
       [ 10,  50],
       [ 25, 145],
       [105,  65],
       [ 15,  30]])

In [58]:
#Allows to retrieve in any order
sample_matrix[:,(3,1)]

array([[ 10, 200],
       [ 50,  10],
       [145,  25],
       [ 65, 105],
       [ 30,  15]])

## Selection

Using brackets for selection based on operators for comparison

In [59]:
simple_array = np.arange(1,31)
simple_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [60]:
simple_array <10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [61]:
boolean_array = simple_array<10

In [62]:
boolean_array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [63]:
simple_array[boolean_array]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
simple_array[simple_array>15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [65]:
a = 11
simple_array[simple_array>a]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30])

# Part 3

# NumPy Operations

## Arithmetic Operations

In [66]:
simple_array = np.arange(0,21)

In [67]:
simple_array + simple_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40])

In [68]:
simple_array * simple_array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400])

In [69]:
simple_array - simple_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
# You get a warning message when dividing 0 by 0, and the value is replaced with nan
simple_array/simple_array

<ipython-input-70-0f95247f8eb3>:2: RuntimeWarning: invalid value encountered in true_divide
  simple_array/simple_array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [71]:
# Here, 10/0 is infinity and not nan - You get a warning message along with it
10/simple_array

<ipython-input-71-1300e7df84ef>:2: RuntimeWarning: divide by zero encountered in true_divide
  10/simple_array


array([        inf, 10.        ,  5.        ,  3.33333333,  2.5       ,
        2.        ,  1.66666667,  1.42857143,  1.25      ,  1.11111111,
        1.        ,  0.90909091,  0.83333333,  0.76923077,  0.71428571,
        0.66666667,  0.625     ,  0.58823529,  0.55555556,  0.52631579,
        0.5       ])

In [72]:
simple_array**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400], dtype=int32)

## Universal Array Functions

Numpy has numerous [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html)

They are mathematical operations that can be performed to the entire array

In [73]:
#Calculating Square Root
np.sqrt(simple_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [74]:
#Calclating exponential values (e^)
np.exp(simple_array)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [75]:
np.max(simple_array) #Can be found out using simple_array.max() format as well

20

In [76]:
np.argmax(simple_array)  #Gives the index position of max value in the array

20

In [77]:
np.sin(simple_array)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525])

In [78]:
np.log(simple_array)

<ipython-input-78-99f05ef9d7e0>:1: RuntimeWarning: divide by zero encountered in log
  np.log(simple_array)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227])

In [79]:
np.cos(simple_array)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462,
        0.40808206])

In [80]:
np.square(simple_array)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400], dtype=int32)

In [81]:
array_2 = np.random.randn(5,5)    #Create a 5x5 matrix with decimal numbers

In [82]:
array_2

array([[-1.58580597,  1.27056837,  0.05385867, -0.52797881, -1.3184431 ],
       [ 1.07135721, -2.00553385, -1.13005453, -0.72837838,  0.87021012],
       [-0.53358059,  0.05930267, -0.94129739, -0.97860255, -0.48141623],
       [-0.51031461, -0.3113105 , -1.36265756, -0.96549078,  0.63039201],
       [ 1.71218934, -0.19824424, -0.6198877 , -0.81826749,  0.39551778]])

In [83]:
np.round(array_2,decimals=2)     #Rounding off the values to 2 decimal places

array([[-1.59,  1.27,  0.05, -0.53, -1.32],
       [ 1.07, -2.01, -1.13, -0.73,  0.87],
       [-0.53,  0.06, -0.94, -0.98, -0.48],
       [-0.51, -0.31, -1.36, -0.97,  0.63],
       [ 1.71, -0.2 , -0.62, -0.82,  0.4 ]])

In [84]:
np.round(array_2)               #Rounding off values to zero decimal places

array([[-2.,  1.,  0., -1., -1.],
       [ 1., -2., -1., -1.,  1.],
       [-1.,  0., -1., -1., -0.],
       [-1., -0., -1., -1.,  1.],
       [ 2., -0., -1., -1.,  0.]])

In [85]:
np.std(array_2)                 # Calculate standard deviation

0.9113853818612282

In [86]:
np.var(array_2)                 # Calculate variance

0.8306233142703366

In [87]:
np.mean(array_2)                # Calculate mean

-0.3581547240867863

In [88]:
#Using the unique function
sports = np.array(['Golf', 'Cricket', 'Football', 'Football','Cricket','cricket','Basketball', 'Baseball'])

np.unique(sports)

array(['Baseball', 'Basketball', 'Cricket', 'Football', 'Golf', 'cricket'],
      dtype='<U10')

### Why do we see cricket twice in above output??

In [89]:
# in1d we can test values in one array - returns boolean output
np.in1d(['Fooseball','Cricket','Baseball'],sports)

array([False,  True,  True])

# Part 4

## NumPy - Array Input and Output

In [90]:
import numpy as np

In [91]:
#Create a simple array
simple_array = np.arange(11)

simple_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
#Save array on hard disk in binary format (file extension is .npy)
np.save('array1',simple_array)

In [93]:
#Change arr
simple_array = np.arange(21)
#Show
simple_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [94]:
#Lets see the original saved copy - This does not get affected by the changes we have made to the simple_array
np.load('array1.npy')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
#Saving multiple arrays into a zip file using savez (file extension is .npz and not .npy)
np.savez('2_arrays.npz',a=simple_array,b=simple_array)

In [96]:
#Now loading multiple arrays using load
archived_arrays = np.load('2_arrays.npz')

#Show
archived_arrays['a']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [97]:
#Saving the arrays as text files

simple_array2 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.savetxt('my_text.txt',simple_array2,delimiter=',')

In [98]:
simple_array2 = np.loadtxt('my_text.txt',delimiter = ',')

simple_array2

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14.]])

### End of NumPy Section